//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOVente
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.COMMANDE = new HashSet<COMMANDE>();
        }
    
        public decimal CLIID { get; set; }
        public string NOM { get; set; }
        public string ADRESSE { get; set; }
        public string VILLE { get; set; }
        public string PAYS { get; set; }
        public string CP { get; set; }
        public string TEL { get; set; }
        public decimal REPID { get; set; }
        public Nullable<decimal> LIMITECREDIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMANDE> COMMANDE { get; set; }
        public virtual EMPLOYE EMPLOYE { get; set; }
    }
}
