//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOVente
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMANDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMANDE()
        {
            this.LIGNECDE = new HashSet<LIGNECDE>();
        }
    
        public decimal CDEID { get; set; }
        public Nullable<System.DateTime> DATECDE { get; set; }
        public string PLANCDE { get; set; }
        public decimal CLIID { get; set; }
        public Nullable<System.DateTime> DATEACHAT { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIGNECDE> LIGNECDE { get; set; }
    }
}
