//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAOVente
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMENCLATURE
    {
        public decimal COMPOSE { get; set; }
        public decimal COMPOSANT { get; set; }
        public Nullable<decimal> QTE { get; set; }
    
        public virtual PRODUIT PRODUIT { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
    }
}
