//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkDBfirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONNE()
        {
            this.RESUME = new HashSet<RESUME>();
        }
    
        public int PersonneId { get; set; }
        public string PersonneName { get; set; }
        public string PersonneUser { get; set; }
        public string PersonnePass { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> Actif { get; set; }
    
        public virtual ROLES ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESUME> RESUME { get; set; }
    }
}
