//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramworkDBfirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIDEO()
        {
            this.RESUME = new HashSet<RESUME>();
        }
    
        public int VideoId { get; set; }
        public string VideoName { get; set; }
        public string VideoPath { get; set; }
        public System.DateTime VideoDateCreation { get; set; }
        public string VideoDescription { get; set; }
        public Nullable<System.DateTime> VideoDateDebut { get; set; }
        public Nullable<long> VideoDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESUME> RESUME { get; set; }
    }
}
